baseurl = "https://vijaypanchal.link/"
languageCode= "en-us"
title = "continuity"
paginate = 7
summaryLength= 20
[params]
dateFormat = "03:04PM, Jan 2, 2006 "
[taxonomies]
  category = 'categories'
  tag = 'tags'
[markup]
[markup.tableOfContents]
    endLevel = 5
    ordered = false
    startLevel = 2