baseurl = "https://vijaypanchal.link/"
languageCode= "en-us"
title = "continuity"
paginate = 6
summaryLength= 20
autonumbering=true
[params]
dateFormat = "Jan 2, 2006 "
[taxonomies]
  category = 'categories'
  tag = 'tags'
[markup]
[markup.tableOfContents]
    endLevel = 5
    ordered = false
    startLevel = 2


[related]
  includeNewer = false
  threshold = 80
  toLower = false
[[related.indices]]
  name = 'tags'
  weight = 100
[[related.indices]]
  name = 'date'
  weight = 10
