#+title: Freedom and Discipline
#+author: Vijay Panchal
#+date: <2022-02-26 Sat>
#+categories[]: philosophy
#+draft: true
#+tags[]: to-think-on, balance
#+thumbnail: freedom-and-discipline/thumbnail.png
#+description: We should allow us to visit deep consequences of freedom.  *What is a freedom ?  How can one define freedom ?*


{{< initial >}}
One evening of this month, oberving my sister's fight with me. I observed that when she is talking, she is using high voice to get value and be listened, i did not find any other reason behind high values. 
{{< /initial >}}

* Knowing two sides of freedom

When we define freedom we should take in action two important parameters 1. *Time* 2. *Ideologies of people*.  Note, that this two parameters are dependant on each other.  I will give example of freedom in our times.  Suppose, one want to speak against some old man or leaders of community, he can.  One want to initiate any business, he can.  If one want to love others wife, he can't because our social law denies it.  so coming to the point freedom is offspring of ideologies of current time.  If Sumerian common man want a slave, he can pursue but the same thing is completely offending in current society, which defines every man has freedom to live his life independently.  There's always society who defines right and wrong for us because it is very complex to handle crowd of people.  Laws are meant to easy our life from burden of chaos of life and society.  From ancient text of should and should not do to happy god to saving our life from judicial custody in modern time. Freedom will give us happiness defined by current order.
We should allow us to visit deep consequences of freedom.  *What is a freedom ?  How can one define freedom ?*
When we define freedom we should take in action two important parameters 1. *Time* 2. *Ideologies of people*.  Note, that this two parameters are dependant on each other.  I will give example of freedom in our times.  Suppose, one want to speak against some old man or leaders of community, he can.  One want to initiate any business, he can.  If one want to love others wife, he can't because our social law denies it.  so coming to the point freedom is offspring of ideologies of current time.  If Sumerian common man want a slave, he can pursue but the same thing is completely offending in current society, which defines every man has freedom to live his life independently.  There's always society who defines right and wrong for us because it is very complex to handle crowd of people.  Laws are meant to easy our life from burden of chaos of life and society.  From ancient text of should and should not do to happy god to saving our life from judicial custody in modern time. Freedom will give us happiness defined by current order.

* Discipline
<2022-03-11 Fri> 
Same as freedom, discipline can be vary from people to people or community to community.  But one thing is common, freedom and discipline may relate or sometime overlap.  I see discipline as conscience control over freedom.


Extremities are bad in every area of life and society, same i can find in freedom. Too less freedom and too much freedom is actually not right.  Balance should be maintain. *how we maintain balance?* Discipline.  Coming to the extreme case, If we look at too less freedom, it give rigid system or mindset.  Too much freedom is chaotic. For example, if some dictator try to maintain everything by his mindset.  Everything is completely in order (disciplined).  Then what do you think will happen? That society can't go further because people will not think creatively.  They will bound by system. *here* =look look here here!= Modern judicial system is one type of discipline.  Observing the intention in this type of system and also every religion system is simply to insure our discipline. But we should know that this systems are meant to be upgraded.  Upgrade means not taking it the extremes but making more balance and making align with current order and mindsets. 




no, one text is text, and text only 

I find quite intresting to compare this relation between freedom and discipline.  Now, whenever i think of discipline i found first image of monks in tibet.  Well, nothing wrong with it, monks are mostly very very disciplined person.  I should compare there freedom to typical person (arbitary subject around world which we does not describe as very[[fn:1][ *]] disciplined).
First of all definitions,  Suppose, we go back into axis of time to land of sumerians, then we see different ideologies, customs and of course definition of freedom.  suppose, you are a sumerian common man. let's see what you can free to do.  Well, you can have some slaves, you can have more than one wife, you're allowed to do common works like farming, fishing, cloth making or some metal work ( i don't know in that time it happen to be).  Now, we will see About discipline. Discipline means you will have strong moral values.  You'll talk calm and firmly.  You'll gain knowledge and question things.  You'll truthful and be good with others.  You'll have good and then i know of 

* Footnotes
:PROPERTIES:
:ID:       1596fe89-86b9-4b1c-a197-e1ff7da705aa
:END:

<<fn:1>> *** : very means not level of monks, and monks means most knowledgeable and refereed for his disciplines.   

HEllo empty here !  ff
