#+title: Thoughts on metaphors 
#+author: vijay panchal
#+date: <2023-08-26 Sat>
#+categories[]: philosophy
#+draft: false
#+tags[]: Physics philosophy
#+image:/images/
#+description: This blog is about my thoughts on metaphores and why i find them interesting and stimulating. read, review, critiseze and debate.




Approximately two years ago, I was reading a book, my favourite book, Gödel, Escher, Bach: an Eternal Golden Braid. It was a very nice read, so stimulating. Around this time, I had also read Bhagavad gita. The common thing between these two is that both are high in metaphors, abstract ideas and I am missing both right now. So, I have a question, why ? Why were these books so stimulating to read and so interesting ? With this blog I will give you my thoughts in this 😌, so, stay tuned and must debate via comments, i would love that.


So, the first thing to do is understand word metaphors. Why are they so interesting ? Basic word definition from wikipedia is as following “A **metaphor** is a [[https://en.m.wikipedia.org/wiki/Figure_of_speech][figure of speech]] that, for [[https://en.m.wikipedia.org/wiki/Rhetoric][rhetorical]] effect, directly refers to one thing by mentioning another.”{{< sidenote >}} wikipedia: https://en.wikipedia.org/wiki/Main_Page {{< /sidenote >}} . Here, we can see that metaphors are explicitly bold by itself, the word rhetorical signifies that, but what we can pursue from this is //linkage//. A linkage of two completely non related or sometimes partially related topics/ideas. This relationship is sometimes quite one to one correspondence but most times in my experience it is not. This basic idea is so powerful that scholars used it throughout history for supplying ideas to other scholars or to the general public. This is so beautiful that artists bring them to their art. But what we are gonna talk about is that of practical (like natural philosophy) and philosophical subjects. I think metaphors have wide use in physics and similar fields, I call them mathematical metaphors. For example, wide use of harmonic motions, fields, potentials, dimensions other than 3 dimensions etc. All of this makes physics quite easy, exciting and stimulating itself also it makes it more general and abstract. We will also talk about why Bhagwad geeta is so stimulating and favourite among scholars throughout Indian history. Disclaimer that my blog is about my ideas and opinions, that is quite variable through masses, if you disagree then please let me know so i could grow.





Let's visit Gödel, Escher, Bach: an Eternal Golden Braid again. Why I liked it so much is that the author did not give directly the core idea. Author made me ride through his rollercoaster. If you start this book you will not immediately realise what it is all about. It will all steadily converge at one core idea and subject. By the title, it's all mysterious itself. But what I realised from this is that in the first half of a book I didn't follow the author's path, I found my own connections with it. The beauty in all this is that I think of the relationship between different fields and ideas. Setting differences apart, we are mostly related with some general knowledge flow. In my view this can be affected by interference with each other's knowledge base. We are not isolated alone or in small groups but constantly in touch with each other's ideas and thinking processes. For example books, which bring our ancestor's ideologies and thinking processes to our eyes. In this modern times I can read ancient Indian sages, roman and greek scholars and modern literature. By all means, this should influence each other in one way or another to make one big flow of common ideas. This is where GEB{{< sidenote >}}Gödel, Escher, Bach: an Eternal Golden Braid{{< /sidenote >}} shines. It brings abstract thought in the first half of the book which directly connects with computer science, natural sciences, mathematical logic, philosophy, art, music and even literature sometimes. This all makes me think, wandering in different fields. It must be stimulating, isn't it?


Let's dive into natural sciences. A physicist will see a pendulum motion and motion of an atom so similar that he will not understand metaphorical logic here. Physicist tools involve dimension manipulation. A three dimensional system or problems is so hard to visualise and understand that he will start with a one dimensional system. He will map out basic ideas into one dimensional system than he will easily solve it and draw conclusions from it then he'll manage to map this system and conclusions to two dimensions, finally he bring it to next and final step - three dimensions, if he is mathematician then he'll generalise it to n dimensions, if possible. Here, I'm not saying that it is unrelated (means dimensions) but can't you see implicit metaphors. I have given you examples of implicit metaphors, so don't think that physics doesn't have any explicit metaphors, we will see that too. Okay, I have a question for you. Has anyone seen any atoms, nuclei or fields? If your answer is no then you can see examples of metaphors **or** If your answer is yes then you're referring to experimental results. Yes, you are right they are one to one correspondence sometimes. What do we say about results? “this phenomenon is observed”. Now, focus on “is”, isn't it a metaphor ? If this is not a metaphor then physics will not evolve, it will be irrelevant at some time and become obsolete. I think the true beauty of physics is its relevance, how it encompasses nature with its own language which is literally a marvel, it's also generalizable to accompany more and it is backed by logic, the true gem of the intellectual flow i was talking about. It is also rhetorical as metaphors. It uses simple metaphors to solve complex problems. A true masterpiece ! Now, suppose there's a flow of electrons in some solid. How can someone analyse it ? Answer is metaphors, the first thing is to visualise it with the flow of liquid, simplified to flow of fluid without obstacles. Now, we put obstacles, this comes from intrinsic behaviour of potentials inside lattice structure. Same as how fluid behaves in a physical situation is mapped into how electrons behave in these potentials. Caution, this is just an approximation that electrons behave as that of rigid ball and potentials as square well type but we can always take better approximations by thinking of the fluid field and electrons trapped in it. See, how physics evolves with better and better metaphors. I think this can be an example of an explicit metaphor. 


Now, we will analyse metaphors in general sense, in philosophies. Best example of this would be Bhagwad Geeta, much more abstract and always relatable. Here, I think metaphors behave slightly differently. I want you to think about single human knowledge as a box/system which can be expanded/evolved. Suppose, in this box we have information which can be used and appended any time. Now, if we take sufficiently flexible metaphors then it'll relate relevant information from conscience. We will think of this information as quantized in nodes for simplification. Now, we bring practical examples here, take one man from the 13th century and one from the current time. Both have different nodes in his box/system. We define output here as a bunch of nodes that make information as we perceive, which will be functions from the box/system and append the existing box/system. Now, metaphors will relate to the box and make output. My idea is that sufficiently flexible metaphors will certainly correlate and will most of the time give outputs. The box from the 13th century and current time can give relevant outputs. This output will be most times related, sometimes the same but always stimulating. Metaphors are functions which operate the system and give rise to new ideas (outputs adding to the box/system). Caution: There's a dark side to it, if we take a system with biassed nodes then metaphors bring biassed outputs which will add up and make a more biassed box/system. These have very bad consequences like extremism and blindness. For example, if you read Bhagwad Geeta prior to a very highly biassed belief that god exists and will make your life great then this certainly will amplify and you would more believe that it'll be so. (Disclaimer, it is just example I'm not atheist and I'm not believer either 😜)


In conclusion, I would say to the reader that metaphors are techniques to get asymptomatically complex ideas, systems and solutions of complex problems. It is a linkage to related knowledge and intellectual flow. Caution that here I am hypothesising that there exists a common system/ideas from which modern knowledge is evolving. These metaphors can be linked and stimulate our mind best. This stimulus then brings joy and a sense of engagement, which most of us crave. Similar to most objects or systems it has certain bad sides, which can be avoided by being open.






