#+title: Python Programming Language 
#+author: Vijay Panchal
#+date: <2022-02-24 Thu>
#+categories[]: Python
#+draft: false
#+tags[]: Programming-languages 101
#+image:/images/
#+toc:false
#+description: Introduction and starting of python's Introductory book. This book will available in chapter via blogs, after that i will upload it as pdf file.

{{< initial >}}
Python is well known <strong>scripting language</strong>. We will see more about scripting languages further. At a time of writing this python is available in <em>version 3.10</em>. You can download from official website of <a href="https://www.python.org/downloads/">python</a>. In this series, i'll go from simple installation to more subtle topics. My idea of audience will be of new students who wanna try python or a science students who starting to learn python or tinker who wanna automate daily stuff in python.
{{< /initial >}}

Python is a [[https://en.wikipedia.org/wiki/High-level_programming_language][high level programming language]], designed by Guido van rossum. It's main objective is code readability. First appeared in 1991, it is one of the leading languages in 2022. It is used in web developing, in data science and analysis, in scietific computing etc. It has reputation for being so slow than other high level programming languages like C, C++, java, Rust etc. Main reason is how it got executed.

In this series, i will follow like rust's official book design. Python is well known so it has many sources but i'll try to align to this rust book design. I will talk about first Installation, Documatation, official writing code style, running hello world program, start a guessing game and than talk about data types etc.

So, be with me in this journey !



#+begin_src python
  import numpy as np
  this insfkj
  lsfljskjfld
  jhjh
#+end_src
