#+title: Stimulus in modern world
#+author: vijay panchal
#+date: <2022-05-05 Thu>
#+categories[]: Philosophy
#+draft: false
#+tags[]: Balance
#+images:
#+description: This blog is on balance from hindu religion to modern philosophy. How balance is necessity. Why do we imbalace it ?

{{< initial >}}
This blog is about balance.  How doing something so much or less defines outcome.  How reading is nice habit but overdoing it, thinking that you will be best scholar is just shadowy dream.  How mobile and internet flooding us in mental stimulus and what it can go bad ? Let's know from mental stimulus.
{{< /initial >}}

From everyday life to doing scholarly work, we are constantly with information.  Information that other scholars or person gifted us.  There thoughts are contained in it, so does there ideologies.  They are also burdened with others, but they invented or more i call it appended it.  Famous line from physics, *"On the soldiers of giants"*- that defines continuity in over knowledge.  Our evolution of information or more i say philosophies and ideologies are continues river of thoughts, which are product of many scholars and normal peoples. So, /stimulus/ is mental process of enjoying bath in this river.  Stimulus is knowing those people, working with them but without them.  We Think our thoughts, on soldier of theirs, we append our knowledge, but our thoughts are new, they are gift to humanity, which were not existed before. Idea s are just outcome of better stimulus and digestion.

Let's now know criticism. /Criticism/ is when we agree or disagree on peoples thoughts.  Criticism is fairly important part of our culture, every thought pass through one of many filters. This filters are also made of previously agreed information.  The main thing is criticism is necessary for society to function properly, not dictation by single idea.

Now, Over stimulus does is fairly simple, when we take information continuously  without digestion of that information.  When we read and only read, we only criticize others idea, we live in others thoughts and never come by our own thought.  We kind of stop our thought process  and only rely on criticizing fairly 'yes' or 'no'.

We lose our thoughts, we depend on external stimulus.  We are addicted then when not a once our mind get  active without stimulus, the more you do more minds want.  We begin to be reactive with world, what author says, what others says.  we loose our proactive ability to make our own thoughts or thinking.

I'm not saying reading is wrong, mobile is wrong, internet is wrong.  I'm saying over doing is wrong.  Balance between criticism and proactive thinking is necessary.  Balance between not reading (not taking any information) and overdoing it.  I'm saying this on persons who uses his mobile, his books continuously and flooded by it. 

What can we do ? The problem is not thinking.  As of my thoughts, i will say read a book then digest it, make some peace and *think*.  Most important thing is our views on thoughts of others, not some random reaction.  Make some time, be active, do some exercise, read a book (or by any mean gain information), then digest it. Go to some peaceful environment and be with yourself.  *Balance is heaven !* 
