#+title: System
#+author: vijay panchal
#+date: <2023-05-21 Sun>
#+categories[]:
#+draft: true
#+tags[]: philosophy
#+image:/images/
#+description: 

From Hinduism to Zorothostrians, intellectuals have thought of a system. A mechanicism which put control on vagueness of our life. In hinduism, we have a word dharma, which abide us to follow duties and texts like bhagawad geeta which signifies behaviour of oneself. Jainism even have well thought dietary laws. Guatam budhha tought us system of one's internal self. We can live as want but why certain ways of life?

Every Action in our life can be assigned to a que. A simple, small and sometimes unnoticable, A thought or physical situations, que can be as simple as glimpse of fastfood cart. How long will you suffer from fight of two opposite thoughts? At last you will be lost to mere thought.

**What can be done about it?**
After reading many self help books i have realized that certain common thing cycles since our religiont times. A moral code which is fundamental pivot of philosophies like stoicism. A system or a code which we have said earlier is sometimes just set of ques. A practical systems can be thought of that way. System such as stoicism strongly argue 5 virtues to a men to follow, courage, .... 

I argue that good side of some religion extrimist is f
